name: Rubocop

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7

      - name: Clone current repo
        uses: actions/checkout@master
        with:
          repository: trinitymonsters/tramway

      - name: Install
        run: |
          gem install rubocop rubocop-rspec rubocop-rails

      - name: Rubocop
        run: |
          rubocop -d
